version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=url
    ports:
      - "3306:3306"
  maven:
    build:
      dockerfile: ./docker/Dockerfile-maven
      context: . 
    volumes:
      - ~/.m2:/root/.m2
      - $PWD:/usr/src/mymaven
    links:
      - "db"
    ports:
      - "8080:8080"
